### ISSUE TITLE
Issues with IE8

### ISSUE THREAD

**Issue by matteoantoci** [Victa/Glisse.js#4]
Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)
Timestamp: Fri, 31 Aug 2012 12:34:16 UTC

Message: Object doesn't support this property or method
Line: 546
Char: 13
Code: 0
URI: http://glisse.victorcoulon.fr/js/glisse.js

The issue can be reproduced clicking on a thumbnail in this page: http://glisse.victorcoulon.fr/example-1/

**Comment by matteoantoci** [comment]
This could be fixed using jQuery.inArray() instead of indexOf() method.

**Comment by Victa** [comment]
ok. i'll take a look, but as mentioned in the readme, it was not my goal to make a compliant plugin.

**Comment by matteoantoci** [comment]
I see, but you could get IE8 partial support with a very small change.
